export const GET_DECK_ACTION = "GET_DECK_ACTION";
export const ADD_CARD_TO_DECK_ACTION = "ADD_CARD_TO_DECK_ACTION";
export const ADD_LANDS_TO_DECK_ACTION = "ADD_LANDS_TO_DECK_ACTION";
export const REMOVE_CARD_FROM_DECK_ACTION = "REMOVE_FROM_DECK_ACTION";
export const REMOVE_LANDS_FROM_DECK_ACTION = "REMOVE_LANDS_FROM_DECK_ACTION";
export const CLEAR_DECK_ACTION = "CLEAR_DECK_ACTION";