export const GET_DECK_ACTION = "GET_DECK_ACTION";
export const ADD_TO_DECK_ACTION = "ADD_TO_DECK_ACTION";
export const REMOVE_FROM_DECK_ACTION = "REMOVE_FROM_DECK_ACTION";
export const CLEAR_DECK_ACTION = "CLEAR_DECK_ACTION";